spring:
  datasource:
    druid:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://localhost:3306/student?characterEncoding=utf-8
     username: root
     password: 123456
  main:
    allow-circular-references: true

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
